title: "就職氷河期世代文系Fランク大学中退エンジニアのリアル"
summary: "就職氷河期世代で残念な学歴と平凡なスキルしか持ち合わせないITエンジニアがこの厳しいIT業界でどうやって生き延びてきたかを自虐的に紹介します。"
topics: [IT業界, 転職]
published: false
price: 200 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6
  - chapter7
  - chapter8
  - chapter9
  - chapter10
